# Generated by Django 2.0.7 on 2018-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipcodeToLatLog',
            fields=[
                ('zipcode', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('lat', models.CharField(max_length=150)),
                ('log', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'zipcode',
            },
        ),
    ]
