# Generated by Django 2.0.7 on 2018-11-19 15:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.FloatField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('is_patient', models.NullBooleanField(default=True)),
                ('is_doctor', models.NullBooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('age', models.FloatField(null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('pincode', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('is_patient', models.NullBooleanField(default=True)),
                ('is_doctor', models.NullBooleanField(default=False)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100, null=True)),
                ('path', models.CharField(default='', max_length=255, null=True, unique=True)),
                ('depth', models.PositiveIntegerField(default=0, null=True)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('last_visit', models.DateField(null=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
