# Generated by Django 2.0.7 on 2018-11-17 20:23

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
