# Generated by Django 2.0.7 on 2018-11-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181117_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='path',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_doctor',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_patient',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='depth',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_doctor',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_patient',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='path',
            field=models.CharField(default='', max_length=255, null=True, unique=True),
        ),
    ]
